### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by zhangyiyan001** [lierererniu/RSSAN-Hyperspectral-Image#1]
您在复现这篇文章的时候，有没有尝试做过消融实验去对比作者所提出的注意力机构对分类精度是否有大的提升？

**Comment by lierererniu** [comment]
您好，我在复现过程中没有做消融实验。我目前在放假，过几天开学我可以把消融实验加上。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lierererniu/RSSAN-Hyperspectral-Image"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月7日(星期六) 上午9:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lierererniu/RSSAN-Hyperspectral-Image] 作者你好 (#1)





 
您在复现这篇文章的时候，有没有尝试做过消融实验去对比作者所提出的注意力机构对分类精度是否有大的提升？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangyiyan001** [comment]
好的，谢谢您
